export const LIST_CREATE_START = 'LIST_CREATE_START';
export const LIST_CREATE_SUCCESS = 'LIST_CREATE_SUCCESS';
export const LIST_CREATE_FAIL = 'LIST_CREATE_FAIL';

export const LIST_EDIT_START = 'LIST_EDIT_START';
export const LIST_EDIT_SUCCESS = 'LIST_EDIT_SUCCESS';
export const LIST_EDIT_FAIL = 'LIST_EDIT_FAIL';

export const LIST_DELETE_START = 'LIST_DELETE_START';
export const LIST_DELETE_SUCCESS = 'LIST_DELETE_SUCCESS';
export const LIST_DELETE_FAIL = 'LIST_DELETE_FAIL';