export const LISTS_FETCH_SUCCESS = 'LISTS_FETCH_SUCCESS';
export const LISTS_FETCH_FAILED = 'LISTS_FETCH_FAILED';

export const LIST_FETCH_SUCCESS = 'LIST_FETCH_SUCCESS';
export const LIST_FETCH_FAILED = 'LIST_FETCH_FAILED';

export const LIST_EDIT_SUCCESS = 'LIST_EDIT_SUCCESS';
export const LIST_EDIT_FAILED = 'LIST_EDIT_FAILED';

export const LIST_CREATE_SUCCESS = 'LIST_CREATE_SUCCESS';
export const LIST_CREATE_FAILED = 'LIST_CREATE_FAILED';

export const LIST_DELETE_SUCCESS = 'LIST_DELETE_START';
export const LIST_DELETE_FAILED = 'LIST_DELETE_FAILED';


export const LIST_ITEM_CREATE_SUCCESS = 'LIST_ITEM_CREATE_SUCCESS';
export const LIST_ITEM_CREATE_FAILED = 'LIST_ITEM_CREATE_FAILED';

export const LIST_ITEM_EDIT_SUCCESS = 'LIST_ITEM_EDIT_SUCCESS';
export const LIST_ITEM_EDIT_FAILED = 'LIST_ITEM_EDIT_FAILED';

export const LIST_ITEM_DELETE_SUCCESS = 'LIST_ITEM_DELETE_SUCCESS';
export const LIST_ITEM_DELETE_FAILED = 'LIST_ITEM_DELETE_FAILED';
